### PR TITLE
Cleanup the Python 3 Port

### PR DESCRIPTION
**Pull request by FreddieWitherden**
These commits fix an issue with the silence context and also transition the code towards a single unified PyFR command.  Documentation is also updated and some command line parsing regressions introduced with Python 3 are resolved.

### CODE REVIEW

**Comment by FreddieWitherden** [comment]
Comments?

**Comment by pv101** [comment]
Does:

2. ``cblas-st`` --- path to shared single-threaded C BLAS library

*string*
*string*

3. ``cblas-mt`` --- path to shared multi-threaded C BLAS library

*string*
*string*

in the User Guide need updating to reflect changes in how BLAS is pointed to?

**Comment by FreddieWitherden** [comment]
Fixed.

**Comment by pv101** [comment]
The request has passed all of @iyer-arvind tests. (@iyer-arvind should also get credit for spotting issue detailed above). So @FreddieWitherden if you are happy, please merge.

**Pull request merged**
