### PR TITLE
Updated User Guide and Developer Guide.

### PR DESCRIPTION
**Pull request by pv101**

### CODE REVIEW

**Comment by FreddieWitherden** [comment]
Would you be okay to document the residual plugin?

**Comment by pv101** [comment]
Is this with reference to definition of ICs et al. in the User Guide, or available functions within Mako templates defined in the Developer Guide?

**Comment by pv101** [comment]
@FreddieWitherden I have now documented the residual plugin.

**Comment by iyer-arvind** [comment]
I think the MAKO can have whatever functionality the backend(s) can provide, I am not sure why we mention them under MAKO documentation specifically. 

I guessed we mention the specific few which are explicitly available for ICs as well as BCs and same as MAKO and guaranteed to work identically on all backends. 

This list is available in nputil file, which is the list I mentioned.

**Comment by FreddieWitherden** [comment]
Are we okay to merge?

**Pull request merged**
