### PR TITLE
Add the TVD-RK3 integrator.

### PR DESCRIPTION
**Pull request by Aerojspark**
Add 3rd order accurate TVD Runge-Kutta integrator

### CODE REVIEW

**Comment by FreddieWitherden** [comment]
Code looks good.  Any thoughts on renaming it to 'tvd-rk3' which might be slightly easier to read?  Otherwise, I'll give it a quick test if it checks out we can merge as-is.

**Comment by Aerojspark** [comment]
I agree to rename it.

**Comment by FreddieWitherden** [comment]
Rename it, do ``git add``, followed by ``git commit --amend`` and a ``git push --force``.

**Comment by FreddieWitherden** [comment]
Be sure to ping Peter closer to the release date to ensure that the documentation is updated.

**Comment by pv101** [comment]
@Aerojspark @FreddieWitherden thanks for this. Yes - please do remind me before the release to make sure the User Guide reflects this new option.

**Pull request merged**
