### PR TITLE
Update User Guide.

### PR DESCRIPTION
**Pull request by pv101**

### CODE REVIEW

**Comment by FreddieWitherden** [comment]
Also remove the documentation for the `format` key.

**Comment by pv101** [comment]
I think I did this? Line 676 removed? Have pack and unpack now died? Shall I remove them from post-p docs?

**Comment by FreddieWitherden** [comment]
I see the change on line 676 but it is also documented immediately above:

```
1. ``format`` --- format of the outputs:

    ``pyfrs-file`` | ``pyfrs-dir``
```

**Comment by FreddieWitherden** [comment]
Pack and unpack have now died as they are not longer necessary with the new file format.  I have removed the documentation I could find in the user guide.  I think everything should merge fine, though.

**Pull request merged**
